In [2]:
import numpy as np

In [6]:
l1 = [1,2,3,4,5]
n1 = np.array([1,2,3,4,5.0])

In [4]:
l1,n1

([1, 2, 3, 4, 5], array([1, 2, 3, 4, 5]))

In [8]:
print(n1)

[1. 2. 3. 4. 5.]


In [10]:
type(n1)

numpy.ndarray

# numpy Library

In [12]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [14]:
np.array((1,2,3,4))

array([1, 2, 3, 4])

In [16]:
np.array(4)

array(4)

In [21]:
l1 = [1,2,3]
l2 = [ l1,l1]
l3 = [[ l1] , [l1]]

In [24]:
l1

[1, 2, 3]

In [26]:
l2

[[1, 2, 3], [1, 2, 3]]

In [28]:
l3

[[[1, 2, 3]], [[1, 2, 3]]]

In [30]:
a1 = np.array([1,2,3])

In [33]:
a1.ndim

1

In [37]:
a2 = np.array ([[1,2,3] , [1,2,3]] )

In [38]:
a2

array([[1, 2, 3],
       [1, 2, 3]])

In [39]:
a2.ndim

2

In [40]:
a3 = np.array ([[[1,2] , [2,4]] , [[ 1,2],[2,4]]]   )

In [41]:
a3

array([[[1, 2],
        [2, 4]],

       [[1, 2],
        [2, 4]]])

In [42]:
a3.ndim

3

In [43]:
a4 = np.array([a3,a3])

In [44]:
a4

array([[[[1, 2],
         [2, 4]],

        [[1, 2],
         [2, 4]]],


       [[[1, 2],
         [2, 4]],

        [[1, 2],
         [2, 4]]]])

In [45]:
a4.ndim

4

# We are able to create multiple Dimension array using Numpy

# How can we define the type of my elements inside np array

In [48]:
n1 = np.array([1,2.0,'python'])

In [49]:
n1

array(['1', '2.0', 'python'], dtype='<U32')

In [55]:
n2 = np.array([1,2.0,3,4,6],dtype = 'int32')

In [56]:
type(n2[0])

numpy.int32

In [3]:
n3 = np.array([1,2,3],dtype='float')

In [4]:
type(n3[0])

numpy.float64

# Creating Numpy Arrays

In [6]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
np.array(list(range(1,10)))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(1,10,2)  # Arange(start, stop,step)

array([1, 3, 5, 7, 9])

In [13]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [16]:
o1 = np.ones((2,2))

In [20]:
type(o1[0][0])

numpy.float64

In [22]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [25]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
np.random.random(5)

array([12.5010746 ,  5.99101199,  6.94488028, 38.29789169, 20.9468678 ])

In [30]:
np.random.random((5,4))

array([[0.40353513, 0.81133918, 0.0851283 , 0.31074532],
       [0.58452876, 0.61213371, 0.94872956, 0.26000163],
       [0.50028602, 0.32337509, 0.68294949, 0.62639145],
       [0.89123997, 0.49269737, 0.99483745, 0.93794901],
       [0.24820218, 0.99741917, 0.56466868, 0.67911473]])

In [31]:
np.linspace(0,10,num=3)

array([ 0.,  5., 10.])

In [36]:
np.linspace(0,10,num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [43]:
np.linspace(0,10,num=7)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

In [39]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Numpy Attributes

In [131]:
n1 = np.arange(1,10,dtype='int8')

In [63]:
n1

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int8)

In [49]:
n1.ndim

1

In [50]:
n1.shape

(9,)

In [64]:
n1.size

9

In [65]:
type(n1[0])

numpy.int8

In [70]:
n1.itemsize

1

In [72]:
n1

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int8)

In [74]:
n1.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int8)

In [76]:
n1.reshape(2,5)

ValueError: cannot reshape array of size 9 into shape (2,5)

# reshape (row, col)

In [78]:
n2 = np.arange(1,17)
n2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [80]:
n2.reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [82]:
n2.reshape(2,2,2,2)

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

In [84]:
n2.reshape(2,8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [86]:
n2.reshape(8,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])

In [89]:
n2.reshape(16)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

# Changing the type of already created Array

In [99]:
n2.astype(np.int8)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
      dtype=int8)

In [103]:
n2 + 2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18])

In [104]:
n2 - 2

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [106]:
n2 / 2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. ])

In [109]:
n2 * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32])

In [111]:
n2%2

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0])

In [113]:
n2==True

array([ True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [115]:
n2 & 1

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0])

In [116]:
n2 // 2

array([0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8])

# Operation with another array

In [119]:
n1 = np.arange(1,5).reshape(2,2)
n2 = np.arange(10,14).reshape(2,2)

In [122]:
n1,n2

(array([[1, 2],
        [3, 4]]),
 array([[10, 11],
        [12, 13]]))

In [124]:
n1 + n2

array([[11, 13],
       [15, 17]])

In [126]:
n1/n2

array([[0.1       , 0.18181818],
       [0.25      , 0.30769231]])

In [128]:
n1 - n2

array([[-9, -9],
       [-9, -9]])

In [129]:
n1 // n2

array([[0, 0],
       [0, 0]])

In [133]:
a1 = np.arange(1,10,dtype='int8')

In [136]:
n1 / n2

array([[0.1       , 0.18181818],
       [0.25      , 0.30769231]])


# Array Functions on Numpy Arrays

max,min,sum,prod
mean,median. std, var

In [139]:
n1

array([[1, 2],
       [3, 4]])

In [140]:
np.sum(n1)

10

In [143]:
np.sum(n1,axis=0) # Column

array([4, 6])

In [144]:
np.sum(n1,axis=1) # Row

array([3, 7])

In [147]:
np.min(n1,axis=1)

array([1, 3])

In [148]:
np.min , np.max , np.sum , np.mean 

(<function min at 0x10ca87170>,
 <function max at 0x10ca86df0>,
 <function sum at 0x10ca863b0>,
 <function mean at 0x10ca8c1b0>)

In [150]:
np.sin(n1)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ]])

In [153]:
np.cos(n1)

array([[ 0.54030231, -0.41614684],
       [-0.9899925 , -0.65364362]])

In [158]:
np.mean(n1,axis=0)

array([2., 3.])

# Dot product

In [159]:
n1

array([[1, 2],
       [3, 4]])

In [162]:
n3 = np.ones((2,5))
n3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [164]:
np.dot(n1,n3)

array([[3., 3., 3., 3., 3.],
       [7., 7., 7., 7., 7.]])

In [166]:
n4 = np.ones((5,2))
n4

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [168]:
np.dot(n1,n4)

ValueError: shapes (2,2) and (5,2) not aligned: 2 (dim 1) != 5 (dim 0)

In [170]:
n1

array([[1, 2],
       [3, 4]])

In [172]:
n1[0]

array([1, 2])

In [176]:
n2 = np.arange(1,5)

In [178]:
n2

array([1, 2, 3, 4])

In [185]:
n2[0::2]

array([1, 3])

In [192]:
for i in n1:
    for j in i:
        print(f'i is {i}')
        print (f'j is {j}')
    


i is [1 2]
j is 1
i is [1 2]
j is 2
i is [3 4]
j is 3
i is [3 4]
j is 4


In [194]:
for i in np.nditer(n1):
    print(f'i is {i}')

i is 1
i is 2
i is 3
i is 4


In [197]:
for elem in np.ravel(n1):
    print(f'i is {elem}')

i is 1
i is 2
i is 3
i is 4


# Broadcasting

In [201]:
n1 = np.arange(1,10).reshape(3,3)
n1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [205]:
n2 = np.arange(1,4).reshape(1,3)
n2

array([[1, 2, 3]])

In [206]:
n1 + n2

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])